import { Download } from 'lucide-react';
import type { QrGeneration } from '../types';
import { formatDateTime } from '../utils/format';
import { EmptyState } from './EmptyState';
import { generateQrDataUrl, downloadDataUrl } from '../utils/qrImage';

interface QRHistoryTableProps {
  rows: QrGeneration[];
  showGeneratedBy?: boolean;
  emptyMessage?: string;
}

export function QRHistoryTable({ rows, showGeneratedBy = false, emptyMessage }: QRHistoryTableProps) {
  if (rows.length === 0) {
    return <EmptyState title={emptyMessage ?? 'No QR codes have been generated yet.'} />;
  }

  async function handleDownload(row: QrGeneration) {
    const dataUrl = await generateQrDataUrl(row.payload);
    downloadDataUrl(dataUrl, `qr-${row.payload}.png`);
  }

  return (
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm">
      <table className="w-full min-w-[720px] text-left text-sm">
        <thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500">
          <tr>
            <th className="px-4 py-3 font-medium">Video</th>
            <th className="px-4 py-3 font-medium">Tracking ID</th>
            <th className="px-4 py-3 font-medium">Payload</th>
            {showGeneratedBy && <th className="px-4 py-3 font-medium">Generated By</th>}
            <th className="px-4 py-3 font-medium">Generated At</th>
            <th className="px-4 py-3 font-medium">
              <span className="sr-only">Actions</span>
            </th>
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-100">
          {rows.map((row) => (
            <tr key={row.id} className="hover:bg-slate-50">
              <td className="px-4 py-3">
                <div className="font-medium text-slate-900">{row.video_name ?? row.video_code}</div>
                <div className="font-mono text-xs text-slate-400">{row.video_code}</div>
              </td>
              <td className="px-4 py-3 font-mono text-slate-700">{row.tracking_id}</td>
              <td className="px-4 py-3 font-mono text-slate-700">{row.payload}</td>
              {showGeneratedBy && (
                <td className="px-4 py-3 text-slate-700">{row.generated_by_username ?? '—'}</td>
              )}
              <td className="px-4 py-3 whitespace-nowrap text-slate-500">{formatDateTime(row.generated_at)}</td>
              <td className="px-4 py-3 text-right">
                <button
                  type="button"
                  onClick={() => handleDownload(row)}
                  aria-label={`Download QR code for ${row.payload}`}
                  className="inline-flex items-center gap-1 rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-100"
                >
                  <Download size={14} aria-hidden="true" />
                  Download
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
